"""initial schema

Revision ID: c05740c0de01
Revises: 
Create Date: 2026-08-07 19:05:18.737316

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c05740c0de01'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Нативные enum-типы объявлены отдельно и с create_type=False. Инлайновый
# sa.Enum внутри create_table пытается выполнить CREATE TYPE на каждой таблице,
# которая тип использует, — второй раз это падает. Поэтому типы создаются один
# раз явно в начале upgrade() и удаляются в конце downgrade(), уже после таблиц:
# пока на тип ссылается хоть одна колонка, DROP TYPE не проходит.
CATEGORY_KIND = postgresql.ENUM("INCOME", "EXPENSE", name="category_kind", create_type=False)
ENTITY_STATUS = postgresql.ENUM("ACTIVE", "INACTIVE", name="entity_status", create_type=False)
PERIOD_STATUS = postgresql.ENUM("OPEN", "CLOSED", name="period_status", create_type=False)
ACCESS_ROLE = postgresql.ENUM("READER", "WRITER", name="access_role", create_type=False)
SHEET_TARGET = postgresql.ENUM(
    "STRUCTURE", "CATEGORIES", "BILLS", "OPERATIONS", "STATISTICS",
    name="sheet_target", create_type=False,
)
SYNC_TASK_KIND = postgresql.ENUM("REDRAW", "IMPORT", name="sync_task_kind", create_type=False)
NOTIFICATION_KIND = postgresql.ENUM(
    "TABLE_READY", "IMPORT_ERROR", "SYNC_FAILED", "ROLLOVER",
    name="notification_kind", create_type=False,
)

ENUM_TYPES = (
    CATEGORY_KIND, ENTITY_STATUS, PERIOD_STATUS, ACCESS_ROLE, SHEET_TARGET,
    SYNC_TASK_KIND, NOTIFICATION_KIND,
)


def upgrade() -> None:
    for enum_type in ENUM_TYPES:
        enum_type.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_users_telegram_id'))
    )
    op.create_table('spreadsheets',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('google_spreadsheet_id', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('reset_day', sa.SmallInteger(), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='Europe/Moscow', nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('reset_day BETWEEN 1 AND 28', name=op.f('ck_spreadsheets_reset_day_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_spreadsheets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spreadsheets')),
    sa.UniqueConstraint('google_spreadsheet_id', name=op.f('uq_spreadsheets_google_spreadsheet_id')),
    sa.UniqueConstraint('user_id', name=op.f('uq_spreadsheets_user_id'))
    )
    op.create_table('cashed_records',
    sa.Column('spreadsheet_id', sa.BigInteger(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_type', sa.String(length=64), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['spreadsheet_id'], ['spreadsheets.id'], name=op.f('fk_cashed_records_spreadsheet_id_spreadsheets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cashed_records')),
    sa.UniqueConstraint('spreadsheet_id', 'product_name', name='uq_cashed_records_spreadsheet_id_product_name')
    )
    op.create_table('categories',
    sa.Column('spreadsheet_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', CATEGORY_KIND, nullable=False),
    sa.Column('status', ENTITY_STATUS, server_default='ACTIVE', nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['spreadsheet_id'], ['spreadsheets.id'], name=op.f('fk_categories_spreadsheet_id_spreadsheets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('id', 'spreadsheet_id', name='uq_categories_id_spreadsheet_id')
    )
    op.create_index('ix_categories_spreadsheet_id_alive', 'categories', ['spreadsheet_id', 'id'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index('ix_categories_title_alive', 'categories', ['spreadsheet_id', sa.literal_column('lower(title)')], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('check_queue_items',
    sa.Column('spreadsheet_id', sa.BigInteger(), nullable=False),
    sa.Column('check_text', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['spreadsheet_id'], ['spreadsheets.id'], name=op.f('fk_check_queue_items_spreadsheet_id_spreadsheets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_check_queue_items'))
    )
    op.create_index('ix_check_queue_items_spreadsheet_id', 'check_queue_items', ['spreadsheet_id', 'id'], unique=False)
    op.create_table('periods',
    sa.Column('spreadsheet_id', sa.BigInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', PERIOD_STATUS, server_default='OPEN', nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date > start_date', name=op.f('ck_periods_dates_order')),
    sa.ForeignKeyConstraint(['spreadsheet_id'], ['spreadsheets.id'], name=op.f('fk_periods_spreadsheet_id_spreadsheets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_periods')),
    sa.UniqueConstraint('id', 'spreadsheet_id', name='uq_periods_id_spreadsheet_id'),
    sa.UniqueConstraint('spreadsheet_id', 'start_date', name='uq_periods_spreadsheet_id_start_date')
    )
    op.create_index('ix_periods_open', 'periods', ['spreadsheet_id'], unique=False, postgresql_where="status = 'OPEN'")
    op.create_table('sources',
    sa.Column('spreadsheet_id', sa.BigInteger(), nullable=False),
    sa.Column('status', ENTITY_STATUS, server_default='ACTIVE', nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('start_balance', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['spreadsheet_id'], ['spreadsheets.id'], name=op.f('fk_sources_spreadsheet_id_spreadsheets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('id', 'spreadsheet_id', name='uq_sources_id_spreadsheet_id')
    )
    op.create_index('ix_sources_spreadsheet_id_alive', 'sources', ['spreadsheet_id', 'id'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index('ix_sources_title_alive', 'sources', ['spreadsheet_id', sa.literal_column('lower(title)')], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('spreadsheet_accesses',
    sa.Column('spreadsheet_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', ACCESS_ROLE, server_default='WRITER', nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['spreadsheet_id'], ['spreadsheets.id'], name=op.f('fk_spreadsheet_accesses_spreadsheet_id_spreadsheets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spreadsheet_accesses')),
    sa.UniqueConstraint('spreadsheet_id', 'email', name='uq_spreadsheet_accesses_spreadsheet_id_email')
    )
    op.create_index('ix_spreadsheet_accesses_pending', 'spreadsheet_accesses', ['spreadsheet_id'], unique=False, postgresql_where='granted_at IS NULL')
    op.create_table('category_associations',
    sa.Column('spreadsheet_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('alias', sa.String(length=64), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('alias = lower(alias)', name=op.f('ck_category_associations_alias_lowercase')),
    sa.CheckConstraint('length(alias) > 0', name=op.f('ck_category_associations_alias_not_empty')),
    sa.ForeignKeyConstraint(['category_id', 'spreadsheet_id'], ['categories.id', 'categories.spreadsheet_id'], name='fk_category_associations_category_id_categories', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category_associations')),
    sa.UniqueConstraint('spreadsheet_id', 'alias', name='uq_category_associations_spreadsheet_id_alias')
    )
    op.create_index('ix_category_associations_category_id', 'category_associations', ['category_id'], unique=False)
    op.create_table('category_product_types',
    sa.Column('spreadsheet_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('product_type', sa.String(length=64), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(product_type) > 0', name=op.f('ck_category_product_types_product_type_not_empty')),
    sa.CheckConstraint('product_type = lower(product_type)', name=op.f('ck_category_product_types_product_type_lowercase')),
    sa.ForeignKeyConstraint(['category_id', 'spreadsheet_id'], ['categories.id', 'categories.spreadsheet_id'], name='fk_category_product_types_category_id_categories', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category_product_types')),
    sa.UniqueConstraint('spreadsheet_id', 'product_type', name='uq_category_product_types_spreadsheet_id_product_type')
    )
    op.create_index('ix_category_product_types_category_id', 'category_product_types', ['category_id'], unique=False)
    op.create_table('records',
    sa.Column('spreadsheet_id', sa.BigInteger(), nullable=False),
    sa.Column('period_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('added_at', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=512), server_default=sa.text("''"), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('product_type', sa.String(length=64), nullable=True),
    sa.Column('check_json', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount <> 0', name=op.f('ck_records_amount_not_zero')),
    sa.ForeignKeyConstraint(['category_id', 'spreadsheet_id'], ['categories.id', 'categories.spreadsheet_id'], name='fk_records_category_id_categories', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['period_id', 'spreadsheet_id'], ['periods.id', 'periods.spreadsheet_id'], name='fk_records_period_id_periods', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['source_id', 'spreadsheet_id'], ['sources.id', 'sources.spreadsheet_id'], name='fk_records_source_id_sources', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['spreadsheet_id'], ['spreadsheets.id'], name=op.f('fk_records_spreadsheet_id_spreadsheets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_records'))
    )
    op.create_index('ix_records_category_id_alive', 'records', ['category_id'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index('ix_records_period_id_alive', 'records', ['period_id', 'id'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index('ix_records_source_id_alive', 'records', ['source_id'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index('ix_records_spreadsheet_id_added_at', 'records', ['spreadsheet_id', 'added_at'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_table('sheet_mappings',
    sa.Column('spreadsheet_id', sa.BigInteger(), nullable=False),
    sa.Column('target', SHEET_TARGET, nullable=False),
    sa.Column('period_id', sa.BigInteger(), nullable=True),
    sa.Column('google_sheet_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(target IN ('OPERATIONS', 'STATISTICS')) = (period_id IS NOT NULL)", name=op.f('ck_sheet_mappings_period_matches_target')),
    sa.ForeignKeyConstraint(['period_id', 'spreadsheet_id'], ['periods.id', 'periods.spreadsheet_id'], name='fk_sheet_mappings_period_id_periods', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spreadsheet_id'], ['spreadsheets.id'], name=op.f('fk_sheet_mappings_spreadsheet_id_spreadsheets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sheet_mappings')),
    sa.UniqueConstraint('spreadsheet_id', 'google_sheet_id', name='uq_sheet_mappings_spreadsheet_id_google_sheet_id'),
    sa.UniqueConstraint('spreadsheet_id', 'target', 'period_id', name='uq_sheet_mappings_key', postgresql_nulls_not_distinct=True)
    )
    op.create_table('sheet_sync_tasks',
    sa.Column('spreadsheet_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', SYNC_TASK_KIND, server_default='REDRAW', nullable=False),
    sa.Column('target', SHEET_TARGET, nullable=False),
    sa.Column('period_id', sa.BigInteger(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.CheckConstraint("kind <> 'IMPORT' OR target IN ('CATEGORIES', 'BILLS')", name=op.f('ck_sheet_sync_tasks_import_target')),
    sa.CheckConstraint("(target IN ('OPERATIONS', 'STATISTICS')) = (period_id IS NOT NULL)", name=op.f('ck_sheet_sync_tasks_period_matches_target')),
    sa.ForeignKeyConstraint(['period_id', 'spreadsheet_id'], ['periods.id', 'periods.spreadsheet_id'], name='fk_sheet_sync_tasks_period_id_periods', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spreadsheet_id'], ['spreadsheets.id'], name=op.f('fk_sheet_sync_tasks_spreadsheet_id_spreadsheets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sheet_sync_tasks')),
    sa.UniqueConstraint('spreadsheet_id', 'kind', 'target', 'period_id', name='uq_sheet_sync_tasks_key', postgresql_nulls_not_distinct=True)
    )
    op.create_index('ix_sheet_sync_tasks_claimable', 'sheet_sync_tasks', ['next_attempt_at'], unique=False, postgresql_where='claimed_at IS NULL')
    op.create_table('source_associations',
    sa.Column('spreadsheet_id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('alias', sa.String(length=64), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('alias = lower(alias)', name=op.f('ck_source_associations_alias_lowercase')),
    sa.CheckConstraint('length(alias) > 0', name=op.f('ck_source_associations_alias_not_empty')),
    sa.ForeignKeyConstraint(['source_id', 'spreadsheet_id'], ['sources.id', 'sources.spreadsheet_id'], name='fk_source_associations_source_id_sources', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_associations')),
    sa.UniqueConstraint('spreadsheet_id', 'alias', name='uq_source_associations_spreadsheet_id_alias')
    )
    op.create_index('ix_source_associations_source_id', 'source_associations', ['source_id'], unique=False)
    op.create_table('transfers',
    sa.Column('spreadsheet_id', sa.BigInteger(), nullable=False),
    sa.Column('period_id', sa.BigInteger(), nullable=False),
    sa.Column('from_source_id', sa.BigInteger(), nullable=False),
    sa.Column('to_source_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('added_at', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=512), server_default=sa.text("''"), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount > 0', name=op.f('ck_transfers_amount_positive')),
    sa.CheckConstraint('from_source_id <> to_source_id', name=op.f('ck_transfers_sources_differ')),
    sa.ForeignKeyConstraint(['from_source_id', 'spreadsheet_id'], ['sources.id', 'sources.spreadsheet_id'], name='fk_transfers_from_source_id_sources', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['period_id', 'spreadsheet_id'], ['periods.id', 'periods.spreadsheet_id'], name='fk_transfers_period_id_periods', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['spreadsheet_id'], ['spreadsheets.id'], name=op.f('fk_transfers_spreadsheet_id_spreadsheets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_source_id', 'spreadsheet_id'], ['sources.id', 'sources.spreadsheet_id'], name='fk_transfers_to_source_id_sources', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfers'))
    )
    op.create_index('ix_transfers_from_source_id_alive', 'transfers', ['from_source_id'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index('ix_transfers_period_id_alive', 'transfers', ['period_id', 'id'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index('ix_transfers_to_source_id_alive', 'transfers', ['to_source_id'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_table('user_notifications',
    sa.Column('spreadsheet_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', NOTIFICATION_KIND, nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['spreadsheet_id'], ['spreadsheets.id'], name=op.f('fk_user_notifications_spreadsheet_id_spreadsheets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_notifications'))
    )
    op.create_index('ix_user_notifications_undelivered', 'user_notifications', ['spreadsheet_id', 'id'], unique=False, postgresql_where='delivered_at IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_notifications_undelivered', table_name='user_notifications', postgresql_where='delivered_at IS NULL')
    op.drop_table('user_notifications')
    op.drop_index('ix_transfers_to_source_id_alive', table_name='transfers', postgresql_where='deleted_at IS NULL')
    op.drop_index('ix_transfers_period_id_alive', table_name='transfers', postgresql_where='deleted_at IS NULL')
    op.drop_index('ix_transfers_from_source_id_alive', table_name='transfers', postgresql_where='deleted_at IS NULL')
    op.drop_table('transfers')
    op.drop_index('ix_source_associations_source_id', table_name='source_associations')
    op.drop_table('source_associations')
    op.drop_index('ix_sheet_sync_tasks_claimable', table_name='sheet_sync_tasks', postgresql_where='claimed_at IS NULL')
    op.drop_table('sheet_sync_tasks')
    op.drop_table('sheet_mappings')
    op.drop_index('ix_records_spreadsheet_id_added_at', table_name='records', postgresql_where='deleted_at IS NULL')
    op.drop_index('ix_records_source_id_alive', table_name='records', postgresql_where='deleted_at IS NULL')
    op.drop_index('ix_records_period_id_alive', table_name='records', postgresql_where='deleted_at IS NULL')
    op.drop_index('ix_records_category_id_alive', table_name='records', postgresql_where='deleted_at IS NULL')
    op.drop_table('records')
    op.drop_index('ix_category_product_types_category_id', table_name='category_product_types')
    op.drop_table('category_product_types')
    op.drop_index('ix_category_associations_category_id', table_name='category_associations')
    op.drop_table('category_associations')
    op.drop_index('ix_spreadsheet_accesses_pending', table_name='spreadsheet_accesses', postgresql_where='granted_at IS NULL')
    op.drop_table('spreadsheet_accesses')
    op.drop_index('ix_sources_title_alive', table_name='sources', postgresql_where='deleted_at IS NULL')
    op.drop_index('ix_sources_spreadsheet_id_alive', table_name='sources', postgresql_where='deleted_at IS NULL')
    op.drop_table('sources')
    op.drop_index('ix_periods_open', table_name='periods', postgresql_where="status = 'OPEN'")
    op.drop_table('periods')
    op.drop_index('ix_check_queue_items_spreadsheet_id', table_name='check_queue_items')
    op.drop_table('check_queue_items')
    op.drop_index('ix_categories_title_alive', table_name='categories', postgresql_where='deleted_at IS NULL')
    op.drop_index('ix_categories_spreadsheet_id_alive', table_name='categories', postgresql_where='deleted_at IS NULL')
    op.drop_table('categories')
    op.drop_table('cashed_records')
    op.drop_table('spreadsheets')
    op.drop_table('users')
    # ### end Alembic commands ###
    for enum_type in ENUM_TYPES:
        enum_type.drop(op.get_bind(), checkfirst=True)
